[book]
title = "Strat9 documentation"
description = "Guide and API reference for Strat9 ABI and userspace syscall layer."
language = "en"
multilingual = false
src = "src"

[output.html]
default-theme = "navy"
git-repository-url = "https://git.strat9-os.org/strat9-os/"
edit-url-template = "https://git.strat9-os.org/strat9-os/edit/main/docs-site/{path}"
