[build]
target = "x86_64-unknown-none"

[target.x86_64-unknown-none]
rustflags = [
    "-C",
    "link-arg=-Lworkspace/kernel",
    "-C",
    "link-arg=-Tworkspace/kernel/linker-limine.ld",
    "-C",
    "link-arg=-no-pie",
    "-C",
    "link-arg=-z",
    "-C",
    "link-arg=nostart-stop-gc",
    "-C",
    "relocation-model=static",
    "-C",
    "code-model=kernel",
]
